<?php

namespace LWS\WOOREWARDS\PRO\Ui\AdminScreens;
// don't call the file directly
if (!defined('ABSPATH')) exit();

class GeneralSettings
{
	static function getTab()
	{
		return array(
			'id'      => 'general_settings',
			'title'   =>  __("General Settings", 'woorewards-pro'),
			'icon'    => 'lws-icon-adv-settings',
			'vertnav' => true,
			'groups'  => array(
				'gensettings' => self::getGroupGeneral(),
				'birthday'    => self::getGroupBirthday(),
				'sponsorship' => self::getGroupSponsorship(),
			)
		);
	}

	static protected function getGroupGeneral()
	{
		return array(
			'id'     => 'settings',
			'icon'	 => 'lws-icon-settings-gear',
			'class'  => 'half',
			'color'  => '#427991',
			'title'  => __("General settings", 'woorewards-pro'),
			'text'   => __("Check the options below according to your needs.", 'woorewards-pro'),
			'fields' => array(
				'c_prefix'  => array(
					'id'    => 'lws_woorewards_reward_coupon_code_prefix',
					'title' => __("Coupon prefix", 'woorewards-pro'),
					'type'  => 'text',
					'extra' => array(
						'size' => '10',
						'help' => __("Set a prefix code that will be added on all coupon codes generated by MyRewards", 'woorewards-pro'),
					)
				),
				'c_length'  => array(
					'id'    => 'lws_woorewards_coupon_code_length',
					'title' => __("Coupon code length", 'woorewards-pro'),
					'type'  => 'text',
					'extra' => array(
						'size' => '3',
						'default' => '10',
						'placeholder' => '10',
						'help' => __("Set the length of the generated coupon code. The length comes in addition to the code prefix.", 'woorewards-pro')
							. ' ' . sprintf(__("Minimum length is %s.", 'woorewards-pro'), \LWS\WOOREWARDS\Unlockables\Coupon::COUPON_CODE_MIN_LENGTH),
					)
				),
				'deep_usersearch' => array(
					'id'    => 'lws_woorewards_admin_userspoints_deep_search',
					'title' => __("Deep customer search", 'woorewards-pro'),
					'type'  => 'box',
					'extra' => array(
						'layout' => 'toggle',
						'default' => 'on',
						'help'   => __("If you have troubles with searching in WooRewards Customers administration screen, disable this option. This will speed up the search but it will take less data into account.", 'woorewards-pro'),
					)
				),
				'enable_leaderboard' => array(
					'id' => 'lws_woorewards_enable_leaderboard',
					'title' => __("Enable the leaderboard shortcode", 'woorewards-pro'),
					'type' => 'box',
					'extra' => array(
						'layout' => 'toggle',
						'help'	=> 	__("If you enable this shortcode, a new option will be added to the user's My Account page.", 'woorewards-pro') . "<br/>" .
							__("The user will have the possibility to set if he/she accepts to appear on the leaderboard or not.", 'woorewards-pro'),
					)
				),
				'show_levels' => array(
					'id' => 'lws_woorewards_show_levels_in_editlist',
					'title' => __("Show levels", 'woorewards-pro'),
					'type' => 'lacselect',
					'extra' => array(
						'maxwidth' => '10em;',
						'mode'     => 'select',
						'help'     => __("Show user level information with its points in customers admin screen.", 'woorewards-pro'),
						'source'   => array(
							array('value' => '', 'label' => __("Points only", 'woorewards-pro')),
							array('value' => 'level', 'label' => __("Level only", 'woorewards-pro')),
							array('value' => 'both', 'label' => __("Points and Level", 'woorewards-pro')),
						),
					)
				),
				'show_priorities' => array(
					'id'    => 'lws_woorewards_show_loading_order_and_priority',
					'title' => __("Show loading orders", 'woorewards-pro'),
					'type'  => 'box',
					'extra' => array(
						'layout' => 'toggle',
						'help'   => __("For some advanced setups, managing loyalty system loading order and event trigger priority could be meaningful.", 'woorewards-pro'),
					)
				),
				'perma_level' => array(
					'id'    => 'lws_woorewards_permanents_through_levels',
					'title' => __("Permanent coupons override all", 'woorewards-pro'),
					'type'  => 'box',
					'extra' => array(
						'layout' => 'toggle',
						'help'   => array(
							__("Permanent coupons will replace any previous permanent coupon reward of the same type owned by the customer inside <b>the same points and rewards system</b>.", 'woorewards-pro'),
							__("Toggle this to let permanent coupons replace previous ones <b>across all</b> points and rewards systems.", 'woorewards-pro'),
						),
					)
				),
			)
		);
	}

	static protected function getGroupBirthday()
	{
		return array(
			'id' 	=> 'wc_birthday',
			'title' => __("Birthday Settings", 'woorewards-pro'),
			'icon'	=> 'lws-icon-birthday-cake',
			'class'	=> 'half',
			'color'  => '#7a6650',
			'text' 	=> __("If you decide to give points for customers birthdays, you should check some of the following options to give customers the opportunity to fill in their birthday date.", 'woorewards-pro'),
			'extra'    => array('doclink' => \LWS\WOOREWARDS\PRO\DocLinks::get('birthday')),
			'fields' => array(
				'birthday_checkout' => array(
					'id' => 'lws_woorewards_registration_birthday_field',
					'title' => __("Display a birthday field in the 'checkout' page when the user register at the same time.", 'woorewards-pro'),
					'type' => 'box',
					'extra' => array(
						'layout' => 'toggle',
					)
				),
				'birthday_register' => array(
					'id' => 'lws_woorewards_myaccount_register_birthday_field',
					'title' => __("Display a birthday field in the 'my account register' page.", 'woorewards-pro'),
					'type' => 'box',
					'extra' => array(
						'layout' => 'toggle',
					)
				),
				'birthday_detail' => array(
					'id' => 'lws_woorewards_myaccount_detail_birthday_field',
					'title' => __("Display a birthday field in the 'my account -> details' page.", 'woorewards-pro'),
					'type' => 'box',
					'extra' => array(
						'layout' => 'toggle',
					)
				),
				'birthday_debug' => array(
					'id' => 'lws_woorewards_myaccount_birthday_debug',
					'title' => __("Display Debug information about birthday point earning in user backend profile.", 'woorewards-pro'),
					'type' => 'box',
					'extra' => array(
						'layout' => 'toggle',
						'default' => 'on',
					)
				),
			)
		);
	}

	static protected function getGroupSponsorship()
	{
		require_once LWS_WOOREWARDS_PRO_INCLUDES . '/ui/editlists/sponsoredreward.php';
		return array(
			'id' 	=> 'sponsorship',
			'icon'	=> 'lws-icon-handshake',
			'color' => '#669876',
			'title'	=> __("Referral Features", 'woorewards-pro'),
			'text' 	=> __("Here, you'll find the different tools customers can user to refer their friends and the reward given to referred users.", 'woorewards-pro') .
				__("To reward the sponsors, either use the dedicated wizard or select an appropriate earning method inside a points and rewards system.", 'woorewards-pro'),
			'extra' => array('doclink' => \LWS\WOOREWARDS\PRO\DocLinks::get('referral')),
			'fields' => array(
				'enable' => array(
					'id'    => 'lws_woorewards_event_enabled_sponsorship',
					'title' => __("Enable Referrals", 'woorewards-pro'),
					'type'  => 'box',
					'extra' => array(
						'layout' => 'toggle',
						'default' => 'on'
					)
				),
				'enableReferral' => array(
					'id'    => 'lws_woorewards_referral_back_give_sponsorship',
					'type'  => 'box',
					'title' => __("Allow referral via referral link", 'woorewards-pro'),
					'extra' => array(
						'default' => 'on',
						'layout' => 'toggle',
						'help' => __("When a visitor comes from a referral link and registers, he will be referred by the user that posted the link.", 'woorewards-pro')
					)
				),
				'tinify' => array(
					'id'    => 'lws_woorewards_sponsorship_tinify_enabled',
					'title' => __("Try to shorten the referral URL", 'woorewards-pro'),
					'type'  => 'box',
					'extra' => array(
						'help' => __('Disable that feature if you encounter plugin conflicts or redirection problems. Disable that feature makes bigger and less readable QR codes.', 'woorewards-pro'),
						'class' => 'lws_checkbox',
						'default' => '',
						'id' => 'lws_woorewards_sponsorship_tinify_enabled',
					)
				),
				'tiny' => array(
					'id'    => 'lws_woorewards_sponsorship_short_url',
					'title' => __("Alternative Short Site URL", 'woorewards-pro'),
					'type'  => 'text',
					'extra' => array(
						'help' => __('To make the QR-Code as simple as possible, you can specify a shorter version of your site URL here that will be used as base for the image generation.', 'woorewards-pro'),
						'placeholder' => \site_url(),
					),
					'require' => array('selector' => '#lws_woorewards_sponsorship_tinify_enabled', 'value' => 'on'),
				),
				'enableSocial' => array(
					'id'    => 'lws_woorewards_socialshare_back_give_sponsorship',
					'type'  => 'box',
					'title' => __("Allow referrals via social share", 'woorewards-pro'),
					'extra' => array(
						'default' => '',
						'layout' => 'toggle',
						'help' => __("When a visitor comes from a link posted on a social network and registers, he will be referred by the user that shared the post.", 'woorewards-pro')
					)
				),
				'max'    => array(
					'id' => 'lws_wooreward_max_sponsorship_count',
					'title' => __("Max referrals per customer", 'woorewards-pro'),
					'type' => 'text',
					'extra' => array(
						'pattern' => '\d+',
						'default' => '0',
						'help' => __("Set the maximum referrals allowed for users. No restriction on empty value or zero (0).", 'woorewards-pro')
					)
				),
				'sp_email_reward' => array(
					'id'    => 'sp_email_reward',
					'type'  => 'editlist',
					'title' => __("Email Referee Reward", 'woorewards-pro'),
					'extra' => array(
						'help' => __("When customers use the email referral feature, you can send an immediate coupon to the email recipient.", 'woorewards-pro'),
						'editlist' => \lws_editlist(
							'Sponsored',
							\LWS\WOOREWARDS\PRO\Ui\Editlists\SponsoredReward::ROW_ID,
							new \LWS\WOOREWARDS\PRO\Ui\Editlists\SponsoredReward(),
							\LWS\Adminpanel\EditList::MDA
						)->setPageDisplay(false)->setCssClass('sponsoredreward')->setRepeatHead(false),
						'function' => function () {
							\wp_enqueue_script('lws-wre-pro-sponsoredreward', LWS_WOOREWARDS_PRO_JS . '/sponsoredreward.js', array('lws-adminpanel-editlist'), LWS_WOOREWARDS_PRO_VERSION, true);
							\wp_enqueue_style('lws-wre-pro-sponsoredreward', LWS_WOOREWARDS_PRO_CSS . '/sponsoredreward.min.css', array('lws-admin-controls'), LWS_WOOREWARDS_PRO_VERSION);
						}
					),
				)
			)
		);
	}
}
